name: GitHub Pages

on:
  workflow_run:
    workflows: ["Run test"]
    branches: [main]
    types:
      - completed
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    strategy:
      matrix:
        python-version:
          - "3.8"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        # with:
        #   version: "0.4.30"

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          # python-version-file: ".python-version"
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      # actions/setup-python を使った方がキャッシュが効くらしいので使わない
      # - name: Set up Python ${{ matrix.python-version }}
      #   run: uv python install ${{ matrix.python-version }}

      - name: Load cached venv
        id: cache-venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/uv.lock') }}

      - name: Install the project
        if: steps.cache-venv.outputs.cache-hit != 'true'
        # run: uv sync --all-extras --dev
        run: uv sync --group docs

      - name: Build the document
        run: make doc-build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
