name: Run test

on:
  push:
  pull_request:

jobs:
  container-test:
    runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         python-version: [3.8, 3.9]
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
